package com.pawanroy1997.versionchecker

import android.os.Build.VERSION.SDK_INT
import android.os.Build.VERSION_CODES

object Checker {
    val isAboveJELLY_BEAN_MR1 = SDK_INT > VERSION_CODES.JELLY_BEAN_MR1
    val isAboveJELLY_BEAN_MR2 = SDK_INT > VERSION_CODES.JELLY_BEAN_MR2
    val isAboveKITKAT = SDK_INT > VERSION_CODES.KITKAT
    val isAboveKITKAT_WATCH = SDK_INT > VERSION_CODES.KITKAT_WATCH
    val isAboveLOLLIPOP = SDK_INT > VERSION_CODES.LOLLIPOP
    val isAboveLOLLIPOP_MR1 = SDK_INT > VERSION_CODES.LOLLIPOP_MR1
    val isAboveM = SDK_INT > VERSION_CODES.M
    val isAboveN = SDK_INT > VERSION_CODES.N
    val isAboveN_MR1 = SDK_INT > VERSION_CODES.N_MR1
    val isAboveO = SDK_INT > VERSION_CODES.O
    val isAboveO_MR1 = SDK_INT > VERSION_CODES.O_MR1
    val isAboveP = SDK_INT > VERSION_CODES.P
    val isAboveQ = SDK_INT > VERSION_CODES.Q
    val isAboveR = SDK_INT > VERSION_CODES.R
    val isAboveS = SDK_INT > VERSION_CODES.S
    val isAboveS_V2 = SDK_INT > VERSION_CODES.S_V2
    val isAboveTIRAMISU = SDK_INT > VERSION_CODES.TIRAMISU

    val isBelowJELLY_BEAN_MR1 = SDK_INT < VERSION_CODES.JELLY_BEAN_MR1
    val isBelowJELLY_BEAN_MR2 = SDK_INT < VERSION_CODES.JELLY_BEAN_MR2
    val isBelowKITKAT = SDK_INT < VERSION_CODES.KITKAT
    val isBelowKITKAT_WATCH = SDK_INT < VERSION_CODES.KITKAT_WATCH
    val isBelowLOLLIPOP = SDK_INT < VERSION_CODES.LOLLIPOP
    val isBelowLOLLIPOP_MR1 = SDK_INT < VERSION_CODES.LOLLIPOP_MR1
    val isBelowM = SDK_INT < VERSION_CODES.M
    val isBelowN = SDK_INT < VERSION_CODES.N
    val isBelowN_MR1 = SDK_INT < VERSION_CODES.N_MR1
    val isBelowO = SDK_INT < VERSION_CODES.O
    val isBelowO_MR1 = SDK_INT < VERSION_CODES.O_MR1
    val isBelowP = SDK_INT < VERSION_CODES.P
    val isBelowQ = SDK_INT < VERSION_CODES.Q
    val isBelowR = SDK_INT < VERSION_CODES.R
    val isBelowS = SDK_INT < VERSION_CODES.S
    val isBelowS_V2 = SDK_INT < VERSION_CODES.S_V2
    val isBelowTIRAMISU = SDK_INT < VERSION_CODES.TIRAMISU
}